 -  name: user creation
    hosts: web
    become: true
    tasks: 
      - name: Create a user 'johnd' with a home directory
        ansible.builtin.user:
          name: johnd
      - name: Create a user 'johnd' with a home directory
        ansible.builtin.user:
          name: johnd
          state: absent
      
      - name: create multi user
        ansible.builtin.user: #useradd "{{ item }}"
          name: "{{ item }}"
          state: present
        loop:  
          - httpd
          - vivek
          - ullas
          - ub
          - vk 
      

      - name: delete multi user
        ansible.builtin.user: #useradd "{{ item }}"
          name: "{{ item }}"
          state: absent
        loop:
          - httpd
          - vivek
          - ullas
          - ub
          - vk
